CREATE SCHEMA IF NOT EXISTS n8n;
GRANT USAGE ON SCHEMA n8n TO n8n;
GRANT CREATE ON SCHEMA n8n TO n8n;
ALTER DEFAULT PRIVILEGES IN SCHEMA n8n GRANT ALL ON TABLES TO n8n;
ALTER DEFAULT PRIVILEGES IN SCHEMA n8n GRANT ALL ON SEQUENCES TO n8n;
